spring:
  application:
    name: java-backend-template
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/property_management
    username: root
    password: 123456
server:
  port: 8080
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0


